<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>834bca1c-b97e-4207-a258-916fc13657d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/brio-cms-root[1]/brio-cms-dashboard[1]/main[@class=&quot;row&quot;]/section[@class=&quot;col-9&quot;]/div[@class=&quot;content&quot;]/brio-cms-add-users[1]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/fieldset[1]/ul[@class=&quot;row&quot;]/li[@class=&quot;col-10&quot;]/brio-cms-multiselect[1]/div[@class=&quot;multi-select&quot;]/div[@class=&quot;list&quot;]/ul[@class=&quot;items&quot;]/li[@class=&quot;item check-box&quot;]/label[1]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
   </webElementXpaths>
</WebElementEntity>
